name: braveart-infra

on:
  push:
    branches: ['feature/**']
    paths: ['infra/**']
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        type: choice
        required: true
        default: prd
        options: [prd]
      terraform-action:
        description: 'Terraform action to perform'
        type: choice
        required: true
        default: plan
        options: [plan, apply, destroy]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: liam-goodchild/pipeline-engineering-templates/.github/workflows/terraform.yml@major/migrating-to-gha
    with:
      environment: ${{ inputs.environment || 'prd' }}
      terraform-action: ${{ inputs.terraform-action || 'plan' }}
      backend-resource-group-name: rg-tfs-platform-${{ inputs.environment || 'prd' }}-uks-01
      backend-storage-account-name: sttfsplatform${{ inputs.environment || 'prd' }}uks01
      backend-container-name: ${{ github.event.repository.name }}
      backend-key: terraform.tfstate
      backend-subscription-id: cefc8742-e1dd-4b24-90a9-07e3d3c80d88
      env-tfvars: vars/${{ inputs.environment || 'prd' }}.tfvars
      global-tfvars: vars/globals.tfvars
      whitelist-agent-ip: false
      ensure-backend-container: false
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
