name: Super-Linter

on:
  workflow_call:
    inputs:
      default-branch:
        description: 'Default branch name'
        type: string
        default: main
      linter-rules-path:
        description: 'Path to linter configuration files'
        type: string
        default: '.github/linters'
      prettier-config-file:
        description: 'Prettier config file name (relative to linter-rules-path)'
        type: string
        default: ''
      prettier-ignore-file:
        description: 'Prettier ignore file name (relative to linter-rules-path)'
        type: string
        default: ''
      checkov-config-file:
        description: 'Checkov config file name'
        type: string
        default: ''
      tflint-config-file:
        description: 'TFLint config file name'
        type: string
        default: ''

permissions:
  contents: read
  statuses: write

jobs:
  lint:
    name: Super-Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: ${{ inputs.default-branch }}
          GITHUB_TOKEN: ${{ github.token }}
          LINTER_RULES_PATH: ${{ inputs.linter-rules-path }}
          VALIDATE_ARM: true
          VALIDATE_BASH: true
          VALIDATE_CHECKOV: true
          VALIDATE_GITLEAKS: true
          VALIDATE_JSON_PRETTIER: true
          VALIDATE_MARKDOWN_PRETTIER: true
          VALIDATE_POWERSHELL: true
          VALIDATE_TERRAFORM_FMT: true
          VALIDATE_TERRAFORM_TFLINT: true
          VALIDATE_YAML_PRETTIER: true
          PRETTIER_CONFIG_FILE: ${{ inputs.prettier-config-file != '' && format('{0}/{1}', inputs.linter-rules-path, inputs.prettier-config-file) || '' }}
          PRETTIER_FILE_NAME: ${{ inputs.prettier-ignore-file != '' && format('{0}/{1}', inputs.linter-rules-path, inputs.prettier-ignore-file) || '' }}
          CHECKOV_FILE_NAME: ${{ inputs.checkov-config-file }}
          TFLINT_CONFIG_FILE: ${{ inputs.tflint-config-file }}
